import { Channel } from "./channel.model";

export class ChannelData {

    get channel () : Channel [] {
        return [
            // new Channel ( 'Интер' , 'Аналоговый Цифровой' ) ,
            // new Channel ( 'НТН' , 'Аналоговый Цифровой' ) ,
            // new Channel ( 'Zoom' , 'Цифровой' ) ,
            // new Channel ( 'Пиксель ТВ' , 'Аналоговый Цифровой' ) ,
            // new Channel ( 'Enter-фильм' , 'Аналоговый Цифровой' ) ,
            // new Channel ( 'Мега' , 'Аналоговый Цифровой' ) ,
            // new Channel ( 'К1' , 'Аналоговый Цифровой' ) ,
            // new Channel ( 'К2' , 'Цифровой' ) ,
            // new Channel ( 'BOLT' , 'Цифровой' ) ,
            // new Channel ( 'Квартал TV' , 'Цифровой' ) ,
            // new Channel ( 'ТРК Украина' , 'Аналоговый Цифровой' ) ,
            // new Channel ( 'НЛО TV' , 'Аналоговый Цифровой' ) ,
            // new Channel ( 'Индиго ТВ' , 'Цифровой' ) ,
            // new Channel ( 'Україна 24' , 'Аналоговый Цифровой' ) ,
            // new Channel ( 'СТБ' , 'Аналоговый Цифровой' ) ,
            // new Channel ( 'ICTV' , 'Аналоговый Цифровой' ) ,
            // new Channel ( 'Новый канал' , 'Аналоговый Цифровой' ) ,
            // new Channel ( 'M1' , 'Цифровой' ) ,
            // new Channel ( 'M2' , 'Аналоговый Цифровой' ) ,
            // new Channel ( 'ОЦЕ' , 'Аналоговый Цифровой' ) ,
            // new Channel ( '1+1' , 'Аналоговый Цифровой' ) ,
            // new Channel ( '2+2' , 'Аналоговый Цифровой' ) ,
            // new Channel ( 'ТЕТ' , 'Аналоговый Цифровой' ) ,
            // new Channel ( 'FilmUaDrama' , 'Цифровой' ) ,
            // new Channel ( 'Paramount COMEDY' , 'Аналоговый Цифровой' ) ,
            // new Channel ( 'УНИАН' , 'Аналоговый Цифровой' ) ,
            // new Channel ( 'ПлюсПлюс' , 'Аналоговый Цифровой' ) ,
            // new Channel ( 'Бигуди' , 'Аналоговый Цифровой' ) ,
            // new Channel ( '7 канал' , 'Аналоговый Цифровой' ) ,
            new Channel ( 'Резерв' , '' ) ,
            // new Channel ( 'Думская.TV' , 'Аналоговый Цифровой' ) ,
            // new Channel ( 'Первый городской' , 'Аналоговый Цифровой' ) ,
            new Channel ( 'Резерв' , '' ) ,
            new Channel ( 'Резерв' , '' ) ,
            // new Channel ( 'Третий цифровой' , 'Аналоговый Цифровой' ) ,
            // new Channel ( 'Медиа Информ' , 'Аналоговый Цифровой' ) ,
            new Channel ( 'Резерв' , '' ) ,
            // new Channel ( 'Центральный' , 'Цифровой' ) ,
            // new Channel ( 'Зоряний' , 'Цифровой' ) ,
            new Channel ( 'Резерв' , '' ) ,
            new Channel ( 'Резерв' , '' ) ,
            // new Channel ( 'Odesa Live' , 'Аналоговый Цифровой' ) ,
            // new Channel ( 'Апостроф' , 'Цифровой' ) ,
            // new Channel ( 'Круг' , 'Аналоговый Цифровой' ) ,
            new Channel ( 'Резерв' , '' ) ,
            // new Channel ( 'Репортер' , 'Аналоговый Цифровой' ) ,
            // new Channel ( 'Моя Одесса' , 'Цифровой' ) ,
            // new Channel ( 'PLUS' , 'Аналоговый Цифровой' ) ,
            // new Channel ( 'Глас' , 'Аналоговый Цифровой' ) ,
            // new Channel ( 'Град' , 'Аналоговый Цифровой' ) ,
            // new Channel ( 'ИТ3' , 'Аналоговый Цифровой' ) ,
            // new Channel ( 'Odessa Fashion' , 'Цифровой' ) ,
            // new Channel ( 'UA:Одеса' , 'Аналоговый Цифровой' ) ,
            // new Channel ( 'Тис-ТВ' , 'Цифровой' ) ,
            // new Channel ( 'MusicBox UA' , 'Цифровой' ) ,
            // new Channel ( '5 Канал' , 'Цифровой' ) ,
            // new Channel ( '6 Соток' , 'Аналоговый Цифровой' ) ,
            // new Channel ( 'Рада' , 'Аналоговый Цифровой' ) ,
            // new Channel ( 'Трофей' , 'Аналоговый Цифровой' ) ,
            // new Channel ( '4Ever Music' , 'Цифровой' ) ,
            // new Channel ( 'Эпоха' , 'Аналоговый Цифровой' ) ,
            // new Channel ( 'Терра' , 'Аналоговый Цифровой' ) ,
            // new Channel ( 'Дача' , 'Аналоговый Цифровой' ) ,
            // new Channel ( 'Фауна' , 'Аналоговый Цифровой' ) ,
            // new Channel ( 'Наука' , 'Аналоговый Цифровой' ) ,
            // new Channel ( 'Киев' , 'Цифровой' ) ,
            // new Channel ( 'Oboz TV' , 'Цифровой' ) ,
            // new Channel ( 'ПравдаТут' , 'Цифровой' ) ,
            // new Channel ( 'Черноморская ТРК' , 'Цифровой' ) ,
            // new Channel ( 'UA:Крим --- Suspilne_Krym' , 'Аналоговый Цифровой' ) ,
            // new Channel ( 'Genuine TV' , 'Аналоговый Цифровой' ) ,
            // new Channel ( 'KRT-K' , 'Цифровой' ) ,
            // new Channel ( 'Прямий' , 'Аналоговый Цифровой' ) ,
            // new Channel ( 'Extreme Sports' , 'Цифровой' ) ,
            // new Channel ( 'UA TV' , 'Цифровой' ) ,
            // new Channel ( 'Телевсесвіт' , 'Цифровой' ) ,
            // new Channel ( 'HD Fashion' , 'Цифровой' ) ,
            // new Channel ( 'UA:Перший' , 'Аналоговый Цифровой' ) ,
            // new Channel ( 'TVIQ' , 'Цифровой' ) ,
            // new Channel ( 'Наталi' , 'Цифровой' ) ,
            // new Channel ( 'UA:Культура --- Суспільне Культура' , 'Аналоговый Цифровой' ) ,
            // new Channel ( 'Сварожичи' , 'Цифровой' ) ,
            // new Channel ( 'Галичина' , 'Цифровой' ) ,
            // new Channel ( 'Еспресо ТВ' , 'Аналоговый Цифровой' ) ,
            // new Channel ( 'Milady' , 'Цифровой' ) ,
            // new Channel ( 'Соната' , 'Цифровой' ) ,
            // new Channel ( 'News 24' , 'Аналоговый Цифровой' ) ,
            // new Channel ( 'Караван TV' , 'Цифровой' ) ,
            // new Channel ( 'Discovery' , 'Аналоговый Цифровой' ) ,
            // new Channel ( 'Animal Planet' , 'Аналоговый Цифровой' ) ,
            // new Channel ( 'Eurosport 1' , 'Аналоговый Цифровой' ) ,
            // new Channel ( 'TLC' , 'Аналоговый Цифровой' ) ,
            // new Channel ( 'UA:Закарпаття --- Суспільне Ужгород' , 'Цифровой' ) ,
            // new Channel ( 'Xsport' , 'Аналоговый Цифровой' ) ,
            // new Channel ( 'Аверс' , 'Цифровой' ) ,
            // new Channel ( 'Закон ТВ' , 'Цифровой' ) ,
            // new Channel ( 'Chanell 4' , 'Аналоговый Цифровой' ) ,
            // new Channel ( 'Первый деловой' , 'Цифровой' ) ,
            // new Channel ( 'UNC' , 'Цифровой' ) ,
            // new Channel ( 'Исландия' , 'Цифровой' ) ,
            // new Channel ( 'Live' , 'Аналоговый Цифровой' ) ,
            // new Channel ( 'Сонце' , 'Аналоговый Цифровой' ) ,
            // new Channel ( 'ATR' , 'Цифровой' ) ,
            // new Channel ( '8 канал --- Vosʹmyy kanal' , 'Цифровой' ) ,
            // new Channel ( 'Надiя' , 'Цифровой' ) ,
            // new Channel ( 'Первый автомобильный' , 'Аналоговый Цифровой' ) ,
            // new Channel ( 'Eko TV ---- ECO TV' , 'Цифровой' ) ,
            // new Channel ( '12 канал Луцк --- Dvanadtsyatyy_Kanal' , 'Цифровой' ) ,
            // new Channel ( 'ЧП ИНФО ---- CHPINFO' , 'Цифровой' ) ,
            // new Channel ( 'Перший Захiдний' , 'Цифровой' ) ,
            // new Channel ( 'Boutique' , 'Цифровой' ) ,
            // new Channel ( 'TV5 Запорожье --- TV-5' , 'Цифровой' ) ,
            // new Channel ( 'BBC World News' , 'Цифровой' ) ,
            // new Channel ( 'Deutsche Welle' , 'Цифровой' ) ,
            // new Channel ( 'France 24' , 'Цифровой' ) ,
            new Channel ( 'Резерв' , '' ) ,
            // new Channel ( 'Euronews' , 'Цифровой' ) ,
            // new Channel ( 'CNN Int.' , 'Цифровой' ) ,
            // new Channel ( 'KBS world' , 'Цифровой' ) ,
            // new Channel ( 'Настоящее время' , 'Цифровой' ) ,
            // new Channel ( 'CNL Украина' , 'Цифровой' ) ,
            // new Channel ( 'OstWest' , 'Цифровой' ) ,
            // new Channel ( 'This is Bulgaria' , 'Цифровой' ) ,
            // new Channel ( 'Travel TV' , 'Цифровой' ) ,
            // new Channel ( 'Deluxe Lounge' , 'Цифровой' ) ,
            // new Channel ( 'Wness TV' , 'Цифровой' ) ,
            // new Channel ( 'Deluxe Music' , 'Цифровой' ) ,
            // new Channel ( 'ROCK TV' , 'Цифровой' ) ,
            // new Channel ( 'Jukebox' , 'Цифровой' ) ,
            // new Channel ( 'Масон ТВ' , 'Цифровой' ) ,
            // new Channel ( 'Travel&Adventure' , 'Цифровой' ) ,
            // new Channel ( 'Кино 1' , 'Аналоговый Цифровой' ) ,
            // new Channel ( 'History HD' , 'Аналоговый Цифровой' ) ,
            // new Channel ( 'Travel HD' , 'Аналоговый Цифровой' ) ,
            // new Channel ( 'Viasat History' , 'Цифровой' ) ,
            // new Channel ( 'Viasat Explorer' , 'Цифровой' ) ,
            // new Channel ( 'Viasat Nature' , 'Цифровой' ) ,
            // new Channel ( 'Black' , 'Цифровой' ) ,
            // new Channel ( 'EU Music' , 'Аналоговый Цифровой' ) ,
            // new Channel ( 'DuckTV+' , 'Цифровой' ) ,
            // new Channel ( 'Duck tv' , 'Цифровой' ) ,
            // new Channel ( 'Tiji' , 'Цифровой' ) ,
            // new Channel ( 'Boomerang' , 'Цифровой' ) ,
            // new Channel ( 'Flix&Snip' , 'Аналоговый Цифровой' ) ,
            // new Channel ( 'Малятко' , 'Цифровой' ) ,
            // new Channel ( 'Cartoon Network' , 'Аналоговый Цифровой' ) ,
            new Channel ( 'Lale' , 'Цифровой' ) ,
            new Channel ( 'Mezzo' , 'Цифровой' ) ,
            new Channel ( 'Niki Kids' , 'Аналоговый Цифровой' ) ,
            new Channel ( 'Niki Junior' , 'Аналоговый Цифровой' ) ,
            new Channel ( 'UA:Донбас' , 'Цифровой' ) ,
            new Channel ( 'Sport1' , 'Цифровой' ) ,
            new Channel ( 'Sport2' , 'Цифровой' ) ,
            new Channel ( 'Setanta Sports' , 'Аналоговый Цифровой' ) ,
            new Channel ( 'Viasat Sport' , 'Цифровой' ) ,
            new Channel ( 'Sport1 Baltic' , 'Цифровой' ) ,
            new Channel ( 'Sport2 Baltic' , 'Цифровой' ) ,
            new Channel ( 'Sport 1HD' , 'Цифровой' ) ,
            new Channel ( 'Fast&Funbox' , 'Цифровой' ) ,
            new Channel ( 'DocuBox' , 'Аналоговый Цифровой' ) ,
            new Channel ( 'Trace Sport HD' , 'Цифровой' ) ,
            new Channel ( 'FilmBox ArtHouse' , 'Аналоговый Цифровой' ) ,
            new Channel ( 'FilmBox' , 'Аналоговый Цифровой' ) ,
            new Channel ( 'FashionBox' , 'Цифровой' ) ,
            new Channel ( '360TuneBox' , 'Аналоговый Цифровой' ) ,
            new Channel ( 'FightBox' , 'Цифровой' ) ,
            new Channel ( 'Nautical' , 'Цифровой' ) ,
            new Channel ( 'SeaTV' , 'Аналоговый Цифровой' ) ,
            new Channel ( 'VIP Premiere' , 'Цифровой' ) ,
            new Channel ( 'VIP Megahit' , 'Цифровой' ) ,
            new Channel ( 'VIP Comedy' , 'Цифровой' ) ,
            new Channel ( 'TV1000 East' , 'Цифровой' ) ,
            new Channel ( 'TV1000 Action East' , 'Цифровой' ) ,
            new Channel ( 'TV1000 World Kino' , 'Аналоговый Цифровой' ) ,
            new Channel ( 'ТВ-1' , 'Цифровой' ) ,
            new Channel ( 'Epic Drama' , 'Цифровой' ) ,
            new Channel ( 'Trace Urban' , 'Цифровой' ) ,
            new Channel ( '4Ever Cinema' , 'Аналоговый Цифровой' ) ,
            new Channel ( 'Дорама' , 'Цифровой' ) ,
            new Channel ( 'AMC' , 'Аналоговый Цифровой' ) ,
            new Channel ( 'Резерв', '' ) ,
            new Channel ( 'КiноКазка' , 'Цифровой' ) ,
            new Channel ( 'Bollywood' , 'Цифровой' ) ,
            new Channel ( 'QuizTV' , 'Цифровой' ) ,
            new Channel ( 'Ua Fashion-TV' , 'Цифровой' )
        ]
    }
    
}