import { Channel } from "./channel.model";

// 'Социальный Аналоговый Цифровой'
// 'Базовый'

export class ChannelData {

    private _channels : Channel [] = [
        new Channel ( 'Интер' , 'Социальный Аналоговый Цифровой' ) ,
        new Channel ( 'НТН' , 'Социальный Аналоговый Цифровой' ) ,
        new Channel ( 'Zoom' , 'Социальный Цифровой' ) ,
        new Channel ( 'Пиксель ТВ' , 'Социальный Аналоговый Цифровой' ) ,
        new Channel ( 'Enter-фильм' , 'Социальный Аналоговый Цифровой' ) ,
        new Channel ( 'Мега' , 'Социальный Аналоговый Цифровой' ) ,
        new Channel ( 'К1' , 'Социальный Аналоговый Цифровой' ) ,
        new Channel ( 'К2' , 'Социальный Цифровой' ) ,
        new Channel ( 'BOLT' , 'Социальный Цифровой' ) ,
        new Channel ( 'Квартал TV' , 'Социальный Цифровой' ) ,
        new Channel ( 'ТРК Украина' , 'Социальный Аналоговый Цифровой' ) ,
        new Channel ( 'НЛО TV' , 'Социальный Аналоговый Цифровой' ) ,
        new Channel ( 'Индиго ТВ' , 'Социальный Цифровой' ) ,
        new Channel ( 'Україна 24' , 'Социальный Цифровой' ) ,
        new Channel ( 'СТБ' , 'Социальный Аналоговый Цифровой' ) ,
        new Channel ( 'ICTV' , 'Социальный Аналоговый Цифровой' ) ,
        new Channel ( 'Новый канал' , 'Социальный Аналоговый Цифровой' ) ,
        new Channel ( 'M1' , 'Социальный Цифровой' ) ,
        new Channel ( 'M2' , 'Социальный Аналоговый Цифровой' ) ,
        new Channel ( 'ОЦЕ' , 'Социальный Аналоговый Цифровой' ) ,
        new Channel ( '1+1' , 'Социальный Аналоговый Цифровой' ) ,
        new Channel ( '2+2' , 'Социальный Аналоговый Цифровой' ) ,
        new Channel ( 'ТЕТ' , 'Социальный Аналоговый Цифровой' ) ,
        new Channel ( 'FilmUaDrama' , 'Социальный Цифровой' ) ,
        new Channel ( 'Paramount COMEDY' , 'Социальный Аналоговый Цифровой' ) ,
        new Channel ( 'УНИАН' , 'Социальный Аналоговый Цифровой' ) ,
        new Channel ( 'ПлюсПлюс' , 'Социальный Аналоговый Цифровой' ) ,
        new Channel ( 'Бигуди' , 'Социальный Аналоговый Цифровой' ) ,
        new Channel ( '7 канал' , 'Социальный Аналоговый Цифровой' ) ,
        new Channel ( 'Резерв' ) ,
        new Channel ( 'Думская.TV' , 'Социальный Аналоговый Цифровой' ) ,
        new Channel ( 'Первый городской' , 'Социальный Аналоговый Цифровой' ) ,
        new Channel ( 'Резерв' ) ,
        new Channel ( 'Резерв' ) ,
        new Channel ( 'Третий цифровой' , 'Социальный Аналоговый Цифровой' ) ,
        new Channel ( 'Медиа Информ' ) ,
        new Channel ( 'Резерв' ) ,
        new Channel ( 'Центральный' ) ,
        new Channel ( 'Зоряний' ) ,
        new Channel ( 'Резерв' ) ,
        new Channel ( 'Резерв' ) ,
        new Channel ( 'Odesa Live' ) ,
        new Channel ( 'Апостроф' , 'Социальный Цифровой' ) ,
        new Channel ( 'Круг' ) ,
        new Channel ( 'Резерв' ) ,
        new Channel ( 'Репортер' , 'Социальный Аналоговый' ) ,
        new Channel ( 'Моя Одесса' ) ,
        new Channel ( 'PLUS' , 'Социальный Аналоговый' ) ,
        new Channel ( 'Глас' , 'Социальный Аналоговый' ) ,
        new Channel ( 'Град' , 'Социальный Аналоговый' ) ,
        new Channel ( 'ИТ3' , 'Социальный Аналоговый' ) ,
        new Channel ( 'Odessa Fashion' ) ,
        new Channel ( 'UA:Одеса' , 'Социальный Аналоговый' ) ,
        new Channel ( 'Тис-ТВ' ) ,
        new Channel ( 'MusicBox UA' ) ,
        new Channel ( '5 Канал' ) ,
        new Channel ( '6 Соток' ) ,
        new Channel ( 'Рада' , 'Социальный Аналоговый' ) ,
        new Channel ( 'Трофей' ) ,
        new Channel ( '4Ever Music' ) ,
        new Channel ( 'Эпоха' ) ,
        new Channel ( 'Терра' ) ,
        new Channel ( 'Дача' ) ,
        new Channel ( 'Фауна' ) ,
        new Channel ( 'Наука' ) ,
        new Channel ( 'Киев' ) ,
        new Channel ( 'Oboz TV' ) ,
        new Channel ( 'ПравдаТут' ) ,
        new Channel ( 'Черноморская ТРК' ) ,
        new Channel ( 'UA:Крим' , 'Социальный Аналоговый' ) ,
        new Channel ( 'Genuine TV' ) ,
        new Channel ( 'KRT-K' ) ,
        new Channel ( 'Прямий' ) ,
        new Channel ( 'Extreme Sports' ) ,
        new Channel ( 'UA TV' ) ,
        new Channel ( 'Телевсесвіт' ) ,
        new Channel ( 'HD Fashion' ) ,
        new Channel ( 'UA:Перший' , 'Социальный Аналоговый' ) ,
        new Channel ( 'TVIQ' ) ,
        new Channel ( 'Наталi' ) ,
        new Channel ( 'UA:Культура' , 'Социальный Аналоговый' ) ,
        new Channel ( 'Сварожичи' ) ,
        new Channel ( 'Галичина' ) ,
        new Channel ( 'Еспресо ТВ' ) ,
        new Channel ( 'Milady' ) ,
        new Channel ( 'Соната' ) ,
        new Channel ( 'News 24' ) ,
        new Channel ( 'Караван TV' ) ,
        new Channel ( 'Discovery' ) ,
        new Channel ( 'Animal Planet' ) ,
        new Channel ( 'Eurosport 1' ) ,
        new Channel ( 'TLC' ) ,
        new Channel ( 'UA:Закарпаття' ) ,
        new Channel ( 'Xsport' ) ,
        new Channel ( 'Аверс' ) ,
        new Channel ( 'Закон ТВ' ) ,
        new Channel ( 'Chanell 4' ) ,
        new Channel ( 'Первый деловой' ) ,
        new Channel ( 'UNC' ) ,
        new Channel ( 'Исландия' ) ,
        new Channel ( 'Live' ) ,
        new Channel ( 'Сонце' ) ,
        new Channel ( 'ATR' ) ,
        new Channel ( '8 канал' ) ,
        new Channel ( 'Надiя' ) ,
        new Channel ( 'Первый автомобильный' ) ,
        new Channel ( 'Eko TV' ) ,
        new Channel ( '12 канал Луцк' ) ,
        new Channel ( 'ЧП ИНФО' ) ,
        new Channel ( 'Перший Захiдний' ) ,
        new Channel ( 'Boutique' ) ,
        new Channel ( 'TV5 Запорожье' ) ,
        new Channel ( 'BBC World News' ) ,
        new Channel ( 'Deutsche Welle' ) ,
        new Channel ( 'France 24' ) ,
        new Channel ( 'Резерв' ) ,
        new Channel ( 'Euronews' ) ,
        new Channel ( 'CNN Int.' ) ,
        new Channel ( 'KBS world' ) ,
        new Channel ( 'Настоящее время' ) ,
        new Channel ( 'CNL Украина' ) ,
        new Channel ( 'OstWest' ) ,
        new Channel ( 'This is Bulgaria' ) ,
        new Channel ( 'Travel TV' ) ,
        new Channel ( 'Deluxe Lounge' ) ,
        new Channel ( 'Wness TV' ) ,
        new Channel ( 'Deluxe Music' ) ,
        new Channel ( 'ROCK TV' ) ,
        new Channel ( 'Jukebox' ) ,
        new Channel ( 'Масон ТВ' ) ,
        new Channel ( 'Travel&Adventure' ) ,
        new Channel ( 'Кино 1' ) ,
        new Channel ( 'History HD' ) ,
        new Channel ( 'Travel HD' ) ,
        new Channel ( 'Viasat History' ) ,
        new Channel ( 'Viasat Explorer' ) ,
        new Channel ( 'Viasat Nature' ) ,
        new Channel ( 'Black' ) ,
        new Channel ( 'EU Music' ) ,
        new Channel ( 'DuckTV+' ) ,
        new Channel ( 'Duck tv' ) ,
        new Channel ( 'Tiji' ) ,
        new Channel ( 'Boomerang' ) ,
        new Channel ( 'Flix&Snip' ) ,
        new Channel ( 'Малятко' ) ,
        new Channel ( 'Cartoon Network' ) ,
        new Channel ( 'Lale' ) ,
        new Channel ( 'Mezzo' ) ,
        new Channel ( 'Niki Kids' ) ,
        new Channel ( 'Niki Junior' ) ,
        new Channel ( 'UA:Донбас' ) ,
        new Channel ( 'Sport1' ) ,
        new Channel ( 'Sport2' ) ,
        new Channel ( 'Setanta Sports' ) ,
        new Channel ( 'Viasat Sport' ) ,
        new Channel ( 'Sport1 Baltic' ) ,
        new Channel ( 'Sport2 Baltic' ) ,
        new Channel ( 'Sport 1HD' ) ,
        new Channel ( 'Fast&Funbox' ) ,
        new Channel ( 'DocuBox' ) ,
        new Channel ( 'Trace Sport HD' ) ,
        new Channel ( 'FilmBox ArtHouse' , 'Социальный Аналоговый' ) ,
        new Channel ( 'FilmBox' ) ,
        new Channel ( 'FashionBox' ) ,
        new Channel ( '360TuneBox' , 'Социальный Аналоговый' ) ,
        new Channel ( 'FightBox' ) ,
        new Channel ( 'Nautical' ) ,
        new Channel ( 'SeaTV' ) ,
        new Channel ( 'VIP Premiere' ) ,
        new Channel ( 'VIP Megahit' ) ,
        new Channel ( 'VIP Comedy' ) ,
        new Channel ( 'TV1000 East' ) ,
        new Channel ( 'TV1000 Action East' ) ,
        new Channel ( 'TV1000 World Kino' ) ,
        new Channel ( 'ТВ-1' ) ,
        new Channel ( 'Epic Drama' ) ,
        new Channel ( 'Trace Urban' ) ,
        new Channel ( '4Ever Cinema' ) ,
        new Channel ( 'Дорама' ) ,
        new Channel ( 'AMC' ) ,
        new Channel ( 'Резерв(181)' ) ,
        new Channel ( 'КiноКазка' ) ,
        new Channel ( 'Bollywood' ) ,
        new Channel ( 'QuizTV' ) ,
        new Channel ( 'Ua Fashion-TV' , 'Социальный Цифровой' )
    ]

    get channels () : Channel [] {
        return this._channels
    }
    
}