import { tChannel } from "./channel.model";
import { ChannelData } from "./channels.data";

export class SotsialnyyTariff {

    static readonly ratiffName = 'Социальный' ;
    static readonly analogChannels : tChannel < 'analog' > [] = [
        ChannelData.M2 ,
        ChannelData.NTN ,
        ChannelData.IT3 ,
        ChannelData.TET ,
        ChannelData.Dva_plyus_dva ,
        ChannelData.Odyn_plyus_odyn ,
        ChannelData.ICTV ,
        ChannelData.STB ,
        ChannelData.Novyy_kanal ,
        ChannelData.TRK_Ukrayina ,
        ChannelData.Inter ,
        ChannelData.Bihudi ,
        ChannelData.OTSE ,
        ChannelData.UNIAN ,
        ChannelData.Paramount_Comedy ,
        ChannelData.PlusPlus ,
        ChannelData.Enter_film ,
        ChannelData.Meha ,
        ChannelData.Piksel ,
        ChannelData.NLO_TV ,
        ChannelData.K1 ,
        ChannelData.Somyy_kanal ,
        ChannelData.Milady_Television ,
        ChannelData.ECO_TV ,
        ChannelData.Pershyy ,
        ChannelData.Karavan_TV ,
        ChannelData.Dumskaya_TV ,
        ChannelData.Reporter ,
        ChannelData.Pervyy_gorodskoy ,
        ChannelData.Natali ,
        ChannelData.Tretiy_tsifrovoy ,
        ChannelData.TuneBox ,
        ChannelData.UA_ODESA ,
        ChannelData.Rada ,
        ChannelData.Suspilne_Krym ,
        ChannelData.Suspilne_Kultura ,
        ChannelData.PLUS ,
        ChannelData.Hlas ,
        ChannelData.Hrad
    ];
    static readonly digitalChannels : tChannel < 'digital' > [] = [
        ChannelData.Inter ,
        ChannelData.NTN ,
        ChannelData.Zoom ,
        ChannelData.Piksel ,
        ChannelData.Enter_film ,
        ChannelData.Meha ,
        ChannelData.K1 ,
        ChannelData.K2 ,
        ChannelData.TRK_Ukrayina ,
        ChannelData.NLO_TV ,
        ChannelData.Indyho_TV ,
        ChannelData.Bolt ,
        ChannelData.Kvartal_TV ,
        ChannelData.Apostrof_TV ,
        ChannelData.Ukrainian_Fashion_TV ,
        ChannelData.Ukrayina_24 ,
        ChannelData.STB ,
        ChannelData.ICTV ,
        ChannelData.Novyy_kanal ,
        ChannelData.M1 ,
        ChannelData.M2 ,
        ChannelData.OTSE ,
        ChannelData.Odyn_plyus_odyn ,
        ChannelData.Dva_plyus_dva ,
        ChannelData.TET ,
        ChannelData.FILMUADrama ,
        ChannelData.Paramount_Comedy ,
        ChannelData.UNIAN ,
        ChannelData.PlusPlus ,
        ChannelData.Bihudi ,
        ChannelData.Somyy_kanal ,
        ChannelData.ReserveG ,
        ChannelData.Dumskaya_TV ,
        ChannelData.Pervyy_gorodskoy ,
        ChannelData.ReserveG ,
        ChannelData.Tretiy_tsifrovoy
    ];

}

export class BazovyyTariff  {

    static readonly ratiffName = 'Базовый' ;
    static readonly analogChannels : tChannel < 'analog' > [] = [
        ChannelData.M2 ,
        ChannelData.NTN , 
        ChannelData.IT3 ,
        ChannelData.TET ,
        ChannelData.Dva_plyus_dva ,
        ChannelData.Odyn_plyus_odyn ,
        ChannelData.ICTV ,
        ChannelData.STB ,
        ChannelData.Novyy_kanal ,
        ChannelData.TRK_Ukrayina ,
        ChannelData.Inter ,
        ChannelData.Bihudi ,
        ChannelData.OTSE ,
        ChannelData.UNIAN ,
        ChannelData.Paramount_Comedy ,
        ChannelData.PlusPlus ,
        ChannelData.Enter_film ,
        ChannelData.Meha ,
        ChannelData.Piksel ,
        ChannelData.NLO_TV ,
        ChannelData.K1 ,
        ChannelData.Somyy_kanal ,
        ChannelData.Milady_Television ,
        ChannelData.ECO_TV ,
        ChannelData.Pershyy ,
        ChannelData.Karavan_TV ,
        ChannelData.Dumskaya_TV ,
        ChannelData.Reporter ,
        ChannelData.Pervyy_gorodskoy ,
        ChannelData.Natali ,
        ChannelData.Tretiy_tsifrovoy ,
        ChannelData.TuneBox ,
        ChannelData.UA_ODESA ,
        ChannelData.Rada ,
        ChannelData.Suspilne_Krym ,
        ChannelData.Suspilne_Kultura ,
        ChannelData.PLUS ,
        ChannelData.Hlas ,
        ChannelData.Hrad ,
        ChannelData.Odesa_live ,
        ChannelData.TV1000_World_Kino ,
        ChannelData.Sontse ,
        ChannelData.Kruh ,
        ChannelData.Terra ,
        ChannelData.Epokha ,
        ChannelData.Fauna ,
        ChannelData.Genuine_TV ,
        ChannelData.Dacha ,
        ChannelData.Nauka ,
        ChannelData.Shist_sotok ,
        ChannelData.News_24 ,
        ChannelData.Espreso_TV ,
        ChannelData.Chanell_4 ,
        ChannelData.Setanta_Sports ,
        ChannelData.Live ,
        ChannelData.Ukrayina_24 ,
        ChannelData.DocuBox ,
        ChannelData.Media_Inform ,
        ChannelData.Pryamyy ,
        ChannelData.Pershyy_avtomobilnyy ,
        ChannelData.Discovery ,
        ChannelData.Animal_Planet ,
        ChannelData.Eurosport_1 ,
        ChannelData.XSPORT ,
        ChannelData.History_HD ,
        ChannelData.Travel_HD ,
        ChannelData.Trofey ,
        ChannelData.EU_Music ,
        ChannelData.AMC ,
        ChannelData.FilmBox ,
        ChannelData.NIKI_Kids ,
        ChannelData.NIKI_Junior ,
        ChannelData.Ever_Cinema ,
        ChannelData.SEA_TV ,
        ChannelData.TLC ,
        ChannelData.FlixSnip ,
        ChannelData.Cartoon_Network , 
        ChannelData.Kino_1
    ];
    static readonly digitalChannels : tChannel < 'digital' > [] = [
        
    ];

}